# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rService.proto\"\x1c\n\x0c\x43heckProduct\x12\x0c\n\x04item\x18\x01 \x01(\t\"*\n\rChangeProduct\x12\x0c\n\x04item\x18\x01 \x01(\t\x12\x0b\n\x03num\x18\x02 \x01(\x05\"8\n\x13TransactionResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x11\n\tinventory\x18\x02 \x01(\x05\x32z\n\x0eProductService\x12\x32\n\tCheckItem\x12\r.CheckProduct\x1a\x14.TransactionResponse\"\x00\x12\x34\n\nChangeItem\x12\x0e.ChangeProduct\x1a\x14.TransactionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CHECKPRODUCT._serialized_start=17
  _CHECKPRODUCT._serialized_end=45
  _CHANGEPRODUCT._serialized_start=47
  _CHANGEPRODUCT._serialized_end=89
  _TRANSACTIONRESPONSE._serialized_start=91
  _TRANSACTIONRESPONSE._serialized_end=147
  _PRODUCTSERVICE._serialized_start=149
  _PRODUCTSERVICE._serialized_end=271
# @@protoc_insertion_point(module_scope)
